"use client";

import { FileText } from "lucide-react";
import { motion } from "framer-motion";

import {
  Bot,
  BarChart3,
  Target,
  MessageSquare,
  TrendingUp,
} from "lucide-react";
import {fadeUp, stagger} from "@/lib/animation"

const features = [
  {
    icon: <Bot size={20} />,
    bg: "#EEF2FF",
    title: "AI Mock Interviews",
    desc: "Real questions generated by Groq AI tailored to your role and difficulty level.",
  },
  {
    icon: <BarChart3 size={20} />,
    bg: "#F0FDF4",
    title: "Instant Scoring",
    desc: "Get accuracy, depth, and clarity scores for every answer with specific improvement tips.",
  },
  {
    icon: <Target size={20} />,
    bg: "#FFF7ED",
    title: "Weak Area Detection",
    desc: "Dashboard tracks your scores by topic and highlights exactly where to focus.",
  },
  {
    icon: <FileText size={20} />,
    bg: "#FFF1F2",
    title: "Resume Analyzer",
    desc: "Upload your resume and get an AI-powered ATS score with section-by-section feedback.",
  },
  {
    icon: <MessageSquare size={20} />,
    bg: "#F0F9FF",
    title: "Question Bank",
    desc: "500+ curated questions organized by role, topic, and difficulty for self-practice.",
  },
  {
    icon: <TrendingUp size={20} />,
    bg: "#FAFAFA",
    title: "Progress Tracking",
    desc: "Score trend charts and session history show your improvement over time.",
  },
];


function Features() {
  return (
    <section id="features" className="py-24 px-6">
      <div className="max-w-5xl mx-auto">
        <p className="text-xs font-semibold text-[#6C63FF] tracking-[2px] uppercase mb-3">
          Features
        </p>
        <h2
          className="font-serif text-4xl md:text-5xl mb-4 max-w-lg"
          style={{ fontFamily: "'Instrument Serif',serif" }}
        >
          Everything you need to prepare
        </h2>
        <p className="text-[#6B6B80] max-w-md leading-relaxed mb-14">
          From AI-generated questions to detailed feedback — PrepAI covers the
          full interview prep cycle.
        </p>
        <motion.div
          variants={stagger}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.2 }}
          className="grid md:grid-cols-3 gap-6"
        >
          {features.map((f) => (
            <motion.div
              key={f.title}
              variants={fadeUp}
              className="bg-white border border-[#E4E4EF] rounded-2xl p-7 hover:-translate-y-1 hover:shadow-[0_12px_40px_rgba(108,99,255,0.1)] hover:border-[rgba(108,99,255,0.3)] transition-all cursor-default"
            >
              <div
                className="w-11 h-11 rounded-xl flex items-center justify-center text-[#6C63FF] mb-4"
                style={{ background: f.bg }}
              >
                {f.icon}
              </div>
              <h3 className="font-semibold mb-2">{f.title}</h3>
              <p className="text-sm text-[#6B6B80] leading-relaxed">{f.desc}</p>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}

export default Features;
